[package]
name = "sapter"
description = "Minesweeper for terminals"
license = "MIT"
version = "0.1.13"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ruscii = "0.3.2"
