[package]
name = "sapter"
version = "0.1.15"
description = "Minesweeper for terminals"
license = "MIT"
edition = "2021"
repository = "https://github.com/finalclass/sapter"

[dependencies]
rand = "0.8.5"
ruscii = "0.3.2"
